baseURL = 'https://hakeemtonalli.github.io/'
languageCode = 'en-us'
title = 'hakeem'
theme="hugo-theme-console-dark"


[params]
  titleCutting = true
  animateStyle = "animated zoomIn fast" 

  [[params.navlinks]]
  name = "photos/"
  url = "photos/"